name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: build --dry-run --stacktrace # just test build configuration

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: check
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: lint
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: assembleRelease