name: "Auto Release"

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          arguments: lint
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          arguments: assembleRelease

  tagged-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build & test"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          prerelease: false
          files: |
            *.aar