name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11

      # 生成javadoc
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: dokkaHtml --stacktrace

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: ayvytr/ayvytr.github.io
          BRANCH: master
          FOLDER: ./flow/build/javadoc
          CLEAN: false
          TARGET_FOLDER: javadocs/flow
